language: objective-c
os: osx
osx_image: xcode10
env:
    global:
    - NSUnbufferedIO=YES
install: ./bin/prepare.sh
script:
    - set -o pipefail
    - swift --version
    - xcodebuild -version
    - xcodebuild -showsdks
    - xcodebuild -list
    - xcodebuild -workspace "TVGemist.xcworkspace" -list
    - xcpretty -v
    - swiftlint version
    - swiftlint
    - xcodebuild -workspace "TVGemist.xcworkspace" -scheme "TVGemist" -sdk "appletvsimulator12.0" -destination "platform=tvOS Simulator,OS=11.0,name=Apple TV 1080p" -configuration Release clean build ONLY_ACTIVE_ARCH=NO CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO RUN_CLANG_STATIC_ANALYZER=YES|xcpretty -c
